name: TinyRedis CI Python

on:
  push:
    branches:
      - main

jobs:

  Deploy:

    runs-on: ubuntu-latest
    steps:
      - name: "Github actions" 
        uses: actions/checkout@v4
      
      - name: "Use python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: "Create python venv"
        run: |
          python -m venv .venv
        
      - name: "Run Requirements"
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: "Run testcses"
        run: |
          python -m pytest tests
      
      - name: "Echo message"
        run: echo "Success!"